/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBoardsNewRouteImport } from './routes/_authenticated/boards.new'
import { Route as AuthenticatedBoardsIdRouteImport } from './routes/_authenticated/boards.$id'
import { Route as AuthenticatedBoardsIdCustomerValidationRouteImport } from './routes/_authenticated/boards.$id.customer-validation'
import { Route as AuthenticatedBoardsIdAnalysisRouteImport } from './routes/_authenticated/boards.$id.analysis'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBoardsNewRoute = AuthenticatedBoardsNewRouteImport.update({
  id: '/_authenticated/boards/new',
  path: '/boards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBoardsIdRoute = AuthenticatedBoardsIdRouteImport.update({
  id: '/_authenticated/boards/$id',
  path: '/boards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBoardsIdCustomerValidationRoute =
  AuthenticatedBoardsIdCustomerValidationRouteImport.update({
    id: '/customer-validation',
    path: '/customer-validation',
    getParentRoute: () => AuthenticatedBoardsIdRoute,
  } as any)
const AuthenticatedBoardsIdAnalysisRoute =
  AuthenticatedBoardsIdAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedBoardsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/boards/$id': typeof AuthenticatedBoardsIdRouteWithChildren
  '/boards/new': typeof AuthenticatedBoardsNewRoute
  '/boards/$id/analysis': typeof AuthenticatedBoardsIdAnalysisRoute
  '/boards/$id/customer-validation': typeof AuthenticatedBoardsIdCustomerValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/boards/$id': typeof AuthenticatedBoardsIdRouteWithChildren
  '/boards/new': typeof AuthenticatedBoardsNewRoute
  '/boards/$id/analysis': typeof AuthenticatedBoardsIdAnalysisRoute
  '/boards/$id/customer-validation': typeof AuthenticatedBoardsIdCustomerValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/boards/$id': typeof AuthenticatedBoardsIdRouteWithChildren
  '/_authenticated/boards/new': typeof AuthenticatedBoardsNewRoute
  '/_authenticated/boards/$id/analysis': typeof AuthenticatedBoardsIdAnalysisRoute
  '/_authenticated/boards/$id/customer-validation': typeof AuthenticatedBoardsIdCustomerValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards/$id'
    | '/boards/new'
    | '/boards/$id/analysis'
    | '/boards/$id/customer-validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards/$id'
    | '/boards/new'
    | '/boards/$id/analysis'
    | '/boards/$id/customer-validation'
  id:
    | '__root__'
    | '/_authenticated/'
    | '/_authenticated/boards/$id'
    | '/_authenticated/boards/new'
    | '/_authenticated/boards/$id/analysis'
    | '/_authenticated/boards/$id/customer-validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBoardsIdRoute: typeof AuthenticatedBoardsIdRouteWithChildren
  AuthenticatedBoardsNewRoute: typeof AuthenticatedBoardsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/boards/new': {
      id: '/_authenticated/boards/new'
      path: '/boards/new'
      fullPath: '/boards/new'
      preLoaderRoute: typeof AuthenticatedBoardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/boards/$id': {
      id: '/_authenticated/boards/$id'
      path: '/boards/$id'
      fullPath: '/boards/$id'
      preLoaderRoute: typeof AuthenticatedBoardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/boards/$id/customer-validation': {
      id: '/_authenticated/boards/$id/customer-validation'
      path: '/customer-validation'
      fullPath: '/boards/$id/customer-validation'
      preLoaderRoute: typeof AuthenticatedBoardsIdCustomerValidationRouteImport
      parentRoute: typeof AuthenticatedBoardsIdRoute
    }
    '/_authenticated/boards/$id/analysis': {
      id: '/_authenticated/boards/$id/analysis'
      path: '/analysis'
      fullPath: '/boards/$id/analysis'
      preLoaderRoute: typeof AuthenticatedBoardsIdAnalysisRouteImport
      parentRoute: typeof AuthenticatedBoardsIdRoute
    }
  }
}

interface AuthenticatedBoardsIdRouteChildren {
  AuthenticatedBoardsIdAnalysisRoute: typeof AuthenticatedBoardsIdAnalysisRoute
  AuthenticatedBoardsIdCustomerValidationRoute: typeof AuthenticatedBoardsIdCustomerValidationRoute
}

const AuthenticatedBoardsIdRouteChildren: AuthenticatedBoardsIdRouteChildren = {
  AuthenticatedBoardsIdAnalysisRoute: AuthenticatedBoardsIdAnalysisRoute,
  AuthenticatedBoardsIdCustomerValidationRoute:
    AuthenticatedBoardsIdCustomerValidationRoute,
}

const AuthenticatedBoardsIdRouteWithChildren =
  AuthenticatedBoardsIdRoute._addFileChildren(
    AuthenticatedBoardsIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBoardsIdRoute: AuthenticatedBoardsIdRouteWithChildren,
  AuthenticatedBoardsNewRoute: AuthenticatedBoardsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
