/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBoardsNewRouteImport } from './routes/_authenticated/boards.new'
import { Route as AuthenticatedBoardsIdRouteImport } from './routes/_authenticated/boards.$id'
import { Route as AuthenticatedBoardsIdStakeholderAlignmentRouteImport } from './routes/_authenticated/boards.$id_.stakeholder-alignment'
import { Route as AuthenticatedBoardsIdProductTechnicalRouteImport } from './routes/_authenticated/boards.$id_.product-technical'
import { Route as AuthenticatedBoardsIdOperationalRouteImport } from './routes/_authenticated/boards.$id_.operational'
import { Route as AuthenticatedBoardsIdCustomerValidationRouteImport } from './routes/_authenticated/boards.$id_.customer-validation'
import { Route as AuthenticatedBoardsIdBusinessRouteImport } from './routes/_authenticated/boards.$id_.business'
import { Route as AuthenticatedBoardsIdAnalysisRouteImport } from './routes/_authenticated/boards.$id_.analysis'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardsNewRoute = AuthenticatedBoardsNewRouteImport.update({
  id: '/boards/new',
  path: '/boards/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardsIdRoute = AuthenticatedBoardsIdRouteImport.update({
  id: '/boards/$id',
  path: '/boards/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardsIdStakeholderAlignmentRoute =
  AuthenticatedBoardsIdStakeholderAlignmentRouteImport.update({
    id: '/boards/$id_/stakeholder-alignment',
    path: '/boards/$id/stakeholder-alignment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoardsIdProductTechnicalRoute =
  AuthenticatedBoardsIdProductTechnicalRouteImport.update({
    id: '/boards/$id_/product-technical',
    path: '/boards/$id/product-technical',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoardsIdOperationalRoute =
  AuthenticatedBoardsIdOperationalRouteImport.update({
    id: '/boards/$id_/operational',
    path: '/boards/$id/operational',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoardsIdCustomerValidationRoute =
  AuthenticatedBoardsIdCustomerValidationRouteImport.update({
    id: '/boards/$id_/customer-validation',
    path: '/boards/$id/customer-validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoardsIdBusinessRoute =
  AuthenticatedBoardsIdBusinessRouteImport.update({
    id: '/boards/$id_/business',
    path: '/boards/$id/business',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoardsIdAnalysisRoute =
  AuthenticatedBoardsIdAnalysisRouteImport.update({
    id: '/boards/$id_/analysis',
    path: '/boards/$id/analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/boards/$id': typeof AuthenticatedBoardsIdRoute
  '/boards/new': typeof AuthenticatedBoardsNewRoute
  '/boards/$id/analysis': typeof AuthenticatedBoardsIdAnalysisRoute
  '/boards/$id/business': typeof AuthenticatedBoardsIdBusinessRoute
  '/boards/$id/customer-validation': typeof AuthenticatedBoardsIdCustomerValidationRoute
  '/boards/$id/operational': typeof AuthenticatedBoardsIdOperationalRoute
  '/boards/$id/product-technical': typeof AuthenticatedBoardsIdProductTechnicalRoute
  '/boards/$id/stakeholder-alignment': typeof AuthenticatedBoardsIdStakeholderAlignmentRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/boards/$id': typeof AuthenticatedBoardsIdRoute
  '/boards/new': typeof AuthenticatedBoardsNewRoute
  '/boards/$id/analysis': typeof AuthenticatedBoardsIdAnalysisRoute
  '/boards/$id/business': typeof AuthenticatedBoardsIdBusinessRoute
  '/boards/$id/customer-validation': typeof AuthenticatedBoardsIdCustomerValidationRoute
  '/boards/$id/operational': typeof AuthenticatedBoardsIdOperationalRoute
  '/boards/$id/product-technical': typeof AuthenticatedBoardsIdProductTechnicalRoute
  '/boards/$id/stakeholder-alignment': typeof AuthenticatedBoardsIdStakeholderAlignmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/boards/$id': typeof AuthenticatedBoardsIdRoute
  '/_authenticated/boards/new': typeof AuthenticatedBoardsNewRoute
  '/_authenticated/boards/$id_/analysis': typeof AuthenticatedBoardsIdAnalysisRoute
  '/_authenticated/boards/$id_/business': typeof AuthenticatedBoardsIdBusinessRoute
  '/_authenticated/boards/$id_/customer-validation': typeof AuthenticatedBoardsIdCustomerValidationRoute
  '/_authenticated/boards/$id_/operational': typeof AuthenticatedBoardsIdOperationalRoute
  '/_authenticated/boards/$id_/product-technical': typeof AuthenticatedBoardsIdProductTechnicalRoute
  '/_authenticated/boards/$id_/stakeholder-alignment': typeof AuthenticatedBoardsIdStakeholderAlignmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/boards/$id'
    | '/boards/new'
    | '/boards/$id/analysis'
    | '/boards/$id/business'
    | '/boards/$id/customer-validation'
    | '/boards/$id/operational'
    | '/boards/$id/product-technical'
    | '/boards/$id/stakeholder-alignment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/'
    | '/boards/$id'
    | '/boards/new'
    | '/boards/$id/analysis'
    | '/boards/$id/business'
    | '/boards/$id/customer-validation'
    | '/boards/$id/operational'
    | '/boards/$id/product-technical'
    | '/boards/$id/stakeholder-alignment'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/'
    | '/_authenticated/boards/$id'
    | '/_authenticated/boards/new'
    | '/_authenticated/boards/$id_/analysis'
    | '/_authenticated/boards/$id_/business'
    | '/_authenticated/boards/$id_/customer-validation'
    | '/_authenticated/boards/$id_/operational'
    | '/_authenticated/boards/$id_/product-technical'
    | '/_authenticated/boards/$id_/stakeholder-alignment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards/new': {
      id: '/_authenticated/boards/new'
      path: '/boards/new'
      fullPath: '/boards/new'
      preLoaderRoute: typeof AuthenticatedBoardsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards/$id': {
      id: '/_authenticated/boards/$id'
      path: '/boards/$id'
      fullPath: '/boards/$id'
      preLoaderRoute: typeof AuthenticatedBoardsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards/$id_/stakeholder-alignment': {
      id: '/_authenticated/boards/$id_/stakeholder-alignment'
      path: '/boards/$id/stakeholder-alignment'
      fullPath: '/boards/$id/stakeholder-alignment'
      preLoaderRoute: typeof AuthenticatedBoardsIdStakeholderAlignmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards/$id_/product-technical': {
      id: '/_authenticated/boards/$id_/product-technical'
      path: '/boards/$id/product-technical'
      fullPath: '/boards/$id/product-technical'
      preLoaderRoute: typeof AuthenticatedBoardsIdProductTechnicalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards/$id_/operational': {
      id: '/_authenticated/boards/$id_/operational'
      path: '/boards/$id/operational'
      fullPath: '/boards/$id/operational'
      preLoaderRoute: typeof AuthenticatedBoardsIdOperationalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards/$id_/customer-validation': {
      id: '/_authenticated/boards/$id_/customer-validation'
      path: '/boards/$id/customer-validation'
      fullPath: '/boards/$id/customer-validation'
      preLoaderRoute: typeof AuthenticatedBoardsIdCustomerValidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards/$id_/business': {
      id: '/_authenticated/boards/$id_/business'
      path: '/boards/$id/business'
      fullPath: '/boards/$id/business'
      preLoaderRoute: typeof AuthenticatedBoardsIdBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards/$id_/analysis': {
      id: '/_authenticated/boards/$id_/analysis'
      path: '/boards/$id/analysis'
      fullPath: '/boards/$id/analysis'
      preLoaderRoute: typeof AuthenticatedBoardsIdAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBoardsIdRoute: typeof AuthenticatedBoardsIdRoute
  AuthenticatedBoardsNewRoute: typeof AuthenticatedBoardsNewRoute
  AuthenticatedBoardsIdAnalysisRoute: typeof AuthenticatedBoardsIdAnalysisRoute
  AuthenticatedBoardsIdBusinessRoute: typeof AuthenticatedBoardsIdBusinessRoute
  AuthenticatedBoardsIdCustomerValidationRoute: typeof AuthenticatedBoardsIdCustomerValidationRoute
  AuthenticatedBoardsIdOperationalRoute: typeof AuthenticatedBoardsIdOperationalRoute
  AuthenticatedBoardsIdProductTechnicalRoute: typeof AuthenticatedBoardsIdProductTechnicalRoute
  AuthenticatedBoardsIdStakeholderAlignmentRoute: typeof AuthenticatedBoardsIdStakeholderAlignmentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBoardsIdRoute: AuthenticatedBoardsIdRoute,
  AuthenticatedBoardsNewRoute: AuthenticatedBoardsNewRoute,
  AuthenticatedBoardsIdAnalysisRoute: AuthenticatedBoardsIdAnalysisRoute,
  AuthenticatedBoardsIdBusinessRoute: AuthenticatedBoardsIdBusinessRoute,
  AuthenticatedBoardsIdCustomerValidationRoute:
    AuthenticatedBoardsIdCustomerValidationRoute,
  AuthenticatedBoardsIdOperationalRoute: AuthenticatedBoardsIdOperationalRoute,
  AuthenticatedBoardsIdProductTechnicalRoute:
    AuthenticatedBoardsIdProductTechnicalRoute,
  AuthenticatedBoardsIdStakeholderAlignmentRoute:
    AuthenticatedBoardsIdStakeholderAlignmentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
